### PR TITLE
Move to python3

### PR DESCRIPTION
**Pull request by movatica**
Python 2 has been officially deprecated and is no longer the default on most systems.
This collection of patches makes the code run with python 3 instead of 2.

### CODE REVIEW

**Comment by ismisepaul** [comment]
There is an error when running this under python3 

command run
`python3 SirepRAT.py <IP-ADDR> GetFileFromDevice --remote_path "C:\Windows\System32\drivers\etc\hosts" --v`


```
Traceback (most recent call last):
  File "SirepRAT.py", line 247, in <module>
    main(args)
  File "SirepRAT.py", line 172, in main
    sirep_result_buffers = sirep_send_command(sock, sirep_command, print_printable_data=args.v or args.vv,
  File "SirepRAT.py", line 105, in sirep_send_command
    sirep_payload = sirep_command.serialize_sirep()
  File "/opt/iot/SirepRAT/models/commands/GetFileFromDeviceCommand.py", line 68, in serialize_sirep
    serialized += struct.pack("II", self.command_type.value, self.payload_length)
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by movatica** [comment]
Thanks for the reply, ismisepaul!
I reproduced it, and it seems there are still a lot of issues to deal with string/binary data handling.
Python3 has a slightly different model on how binary and string data is handled and converted.
I'm working on it and update the branch accordingly.

**Comment by dorazouri** [comment]
Hi @movatica, thanks a lot (!) for jumping on this important task of porting it to python 3.
Please update when the PR is ready for review and merge.
I will happily feature your contribution on the main page when this is done, as it is a major level up for this repo.

**Comment by movatica** [comment]
@dorazouri: I think I got all issues fixed now, please check if you can still find issues!
The whole binary handling got a huge refactoring.

@ismisepaul: Your testcase works for me now, please verify!

**Comment by movatica** [comment]
Besides, I expect this patchset to break python2 compatibility.
I don't care, because python2 got EOL already, but that may break your usecase.

**Comment by ismisepaul** [comment]
> case works for me now, please ver

@movatica I can confirm my test case works now. Thanks for the great work!

**Comment by dorazouri** [comment]
@movatica This is awesome! I've run test cases of all commands, comparing to the old 2.7 output, all works smoothly.
Your branch was merged into master and thanks to you SirepRAT now runs on Python3 (naturally no backwards compatibility to python2.7)

**Comment by pwnfoo** [comment]
Awesome work @movatica! 🎉

BlackArch now uses Py3 to run SirepRAT: https://github.com/BlackArch/blackarch/pull/2956

**Pull request merged**
